apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: petclinic
  labels:
    app.kubernetes.io/name: petclinic
    app.kubernetes.io/component: service

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: petclinic

  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http